Table alumnos {
    id int [pk, increment] // Primary key
    nombre varchar
    password varchar
    correo_electronico varchar
    creacion varchar
    actualizacion varchar
    foto_perfil varchar // Ruta o nombre de imagen
    estado enum ('activo', 'inactivo') // Controla acceso del usuario
    ultimo_acceso datetime // Última vez que inició sesión
    fecha_creacion datetime
    fecha_actualizacion datetime
} 