Table asistencia {
    id int [pk, increment] // Primary key
    tutores_id int [ref: > tutores.id] 
    estudiantes_id int [ref: > estudiantes.id] 
    periodo_id int [ref: > periodos.id] 
    sesion int 
    fecha date 
    estado enum('si','no','np','justificado') default 'si'
    observaciones text 
    created_at timestamp
    updated_at timestamp
}
