Table estudiantes {
    id int [pk, increment] // Primary key
    users_id int [ref: > users.id] 
    //datos generales 
    matricula varchar(20)
    nombre varchar(100) 
    apellidos varchar(100)
    curp varchar
    fecha_nacimiento date
    genero enum('masculino', 'femenino', 'otro')
    //informacion de contacto
    correo_institucional varchar(150)
    telefono_celular varchar(20) 
    domicilio text 
    carrera varchar(100) 
    semestre int 
    estado enum('activo', 'baja_temporal', 'baja_definitiva', 'egresado')
    fecha_ingreso date
    fecha_egreso date
    created_at timestamp
    updated_at timestamp
}