Table individuales {
    id int [pk, increment] // Primary key
    periodos_id int [ref: > periodos.id]
    tutores_id int [ref: > tutores.id] 
    alumnos_id int [ref: > alumnos.id]
    requiere_canalizacion enum('si','no') default 'no' //si la respuesta es un si se le dara la opcion de contestar la encuesta de canalizaciones 
    motivo text 
    estado enum('pendiente','en_proceso','completado') default 'pendiente'
    created_at timestamp
    updated_at timestamp
}
