Table pats {
    id int [pk, increment] // Primary key
    tutores_id int [ref: > tutores.id] 
    grupos_id int [ref: > grupos.id] 
    periodo_id int [ref: > periodo.id] 
    actividad varchar(150) 
    responsable varchar(100) // Responsable de la actividad (puede ser el tutor o un estudiante)
    semana_planeada varchar(50) 
    semana_real varchar(50) 
    estado enum('pendiente','en_proceso','completado') default 'pendiente' 
    created_at timestamp
    updated_at timestamp
}