Table periodo {
    id int [pk, increment] // Primary key
    estudiantes_id int [ref: > estudiantes.id]
    nombre_periodo varchar(50)
    año_periodo int 
    fecha_inicio date
    fecha_fin date
    descripcion text
    estado enum('activo', 'inactivo', 'finalizado')
    created_at timestamp
    updated_at timestamp
}
