Table tutores {
    id int [pk, increment] // Primary key
    users_id int [ref: > users.id] //relación con tabla usuarios 
    //datos generales
    nombre varchar
    apellidos varchar
    curp varchar
    fecha_nacimiento date
    sexo enum('masculino', 'femenino', 'otro')
   //informacion de contacto
     correo_electronico varchar [unique]
    telefono varchar
    departamento varchar
    //informacion adiccional
    rfc varchar
    nivel_estudios varchar
    descripcion_estudios text
    estado enum('activo', 'inactivo') // Estado del tutor
    fecha_registro datetime
    fecha_actualizacion datetime
}