Table tutorado {
    id int [pk, increment] // Primary key
    estudiantes_id int [ref: > estudiantes.id] // Relación con la tabla estudiantes
    grupo_id int [ref: > grupo.id] 
    periodo_id int [ref: > periodo.id]  
    tutores_id int [ref: > tutores.id] 
    nombre varchar(100)
    apellido_paterno varchar(50)
    apellido_materno varchar(50)
    matricula varchar(20) [unique]
    carrera varchar(100)
    semestre int
    edad int
    genero enum('masculino', 'femenino', 'otro')
    correo_electronico varchar(150)
    telefono varchar(20)
    direccion text
    estado enum('activo','baja_temporal','baja_definitiva','egresado') default 'activo'
    observaciones text
    created_at timestamp
    updated_at timestamp
}
